#!/bin/sh
# --------------------------------------------------------
# old - Opens the latest file in a directory in your editor
# --------------------------------------------------------
# You would put this code in a directory that's in your
# path, like ~/bin (PATH=~/bin:$PATH in your .bashrc to
# add a directory like that to your path.)
# The invokation syntax is the same as that of the
# function.
# --------------------------------------------------------
# Example usage:
# old
# old path/to/directory
# --------------------------------------------------------


unset latest
for file in "${1:-.}"/*
do
    if [ -f "$file" ]
    then
        latest=${latest-$file}
        find "$file" -prune -newer "$latest" | read -r dummy && latest=$file
    fi
done
test -e "$latest" && exec "$EDITOR" "$latest"

# --------------------------------------------------------
